const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 8787);
const rooms = new Map();
const RANKS = [9, 11, 12, 13, 14, 15];
const SUITS = [0, 1, 2, 3];
const SUIT_SYMBOLS = ['♣', '♦', '♥', '♠'];

const makeCard = (rank, suit) => ({ id: crypto.randomUUID(), rank, suit });
const makeDeck = () => SUITS.flatMap(suit => RANKS.flatMap(rank => [makeCard(rank, suit), makeCard(rank, suit)]));
const cardPoints = rank => rank >= 13 ? 1 : 0;

function shuffle(cards) { for (let i = cards.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [cards[i], cards[j]] = [cards[j], cards[i]]; } return cards; }
function sortHand(cards) { const suitOrder = [0, 1, 3, 2]; return cards.sort((a, b) => suitOrder.indexOf(a.suit) - suitOrder.indexOf(b.suit) || a.rank - b.rank); }
function countMeld(hand, trump) { const count = (suit, rank) => hand.filter(c => c.suit === suit && c.rank === rank).length; let total = [15, 14, 13, 12, 11].every(rank => count(trump, rank)) ? 15 : 0; for (const suit of SUITS) if (count(suit, 13) && count(suit, 12)) total += (suit === trump ? 4 : 2) * (count(suit, 13) > 1 && count(suit, 12) > 1 ? 2 : 1); for (const [rank, value] of [[15, 10], [13, 8], [12, 6], [11, 4]]) if (SUITS.every(suit => count(suit, rank))) total += value; const pinochles = Math.min(count(3, 12), count(1, 11)); return total + (pinochles === 2 ? 30 : pinochles ? 4 : 0) + count(trump, 9); }
function scoringCards(hand, trump) { const selected = new Map(); const add = (suit, rank, copies = 1) => hand.filter(c => c.suit === suit && c.rank === rank).slice(0, copies).forEach(c => selected.set(c.id, c)); const count = (suit, rank) => hand.filter(c => c.suit === suit && c.rank === rank).length; if ([15, 14, 13, 12, 11].every(rank => count(trump, rank))) [15, 14, 13, 12, 11].forEach(rank => add(trump, rank)); for (const suit of SUITS) { const copies = Math.min(count(suit, 13), count(suit, 12)); if (copies) { add(suit, 13, copies); add(suit, 12, copies); } } for (const rank of [15, 13, 12, 11]) if (SUITS.every(suit => count(suit, rank))) SUITS.forEach(suit => add(suit, rank)); const pinochles = Math.min(count(3, 12), count(1, 11)); if (pinochles) { add(3, 12, pinochles); add(1, 11, pinochles); } add(trump, 9, count(trump, 9)); return sortHand([...selected.values()]); }
function legalCards(hand, trick, trump) { if (!trick.length) return hand; const leadSuit = trick[0].card.suit; const followSuit = hand.filter(c => c.suit === leadSuit); if (followSuit.length) return followSuit; const trumps = hand.filter(c => c.suit === trump); return trumps.length ? trumps : hand; }
function trickWinner(trick, trump) { let winner = trick[0]; for (const play of trick.slice(1)) { const card = play.card, best = winner.card; if ((card.suit === best.suit && card.rank > best.rank) || (card.suit === trump && best.suit !== trump)) winner = play; } return winner; }
function aiMove(player, trick, trump) { const options = legalCards(player.hand, trick, trump); if (!trick.length) return options.reduce((highest, card) => card.rank > highest.rank ? card : highest); const best = trickWinner(trick, trump).card; return options.find(card => (card.suit === best.suit && card.rank > best.rank) || (card.suit === trump && best.suit !== trump)) || options.slice().sort((a, b) => a.rank - b.rank)[0]; }
function newCode() { let code; do code = crypto.randomBytes(2).toString('hex').toUpperCase(); while (rooms.has(code)); return code; }
function addEvent(room, text) { room.history.push(text); if (room.history.length > 14) room.history.shift(); }
function finishBidding(room) { if (room.active.filter(Boolean).length > 1) return; if (room.bidWinner === null) { room.bidWinner = room.dealer; room.bid = 20; room.message = `Everyone passed. ${room.players[room.dealer].name} is stuck with 20.`; addEvent(room, room.message); } room.phase = 'trump'; room.turn = room.bidWinner; }

function view(room, playerId) { const player = room.players.find(p => p.id === playerId); const revealMeld = ['meld-result', 'playing', 'trick-result', 'round-result'].includes(room.phase); return { code: room.code, phase: room.phase, turn: room.turn, dealer: room.dealer, gameNumber: room.gameNumber, handsInGame: room.handsInGame, bid: room.bid, bidWinner: room.bidWinner, trump: room.trump, scores: room.scores, trickPoints: room.trickPoints, trick: room.trick, lastTrick: room.lastTrick, message: room.message, history: room.history, players: room.players.map(p => ({ id: p.id, name: p.name, ai: p.ai, seat: p.seat, meld: revealMeld ? p.meld : 0, meldCards: revealMeld ? p.meldCards : [] })), hand: player?.hand || [] }; }
function finishRound(room) { room.trickPoints[room.lastWinner % 2 ? 'them' : 'us']++; const usMeld = room.players.filter(p => p.seat % 2 === 0).reduce((sum, p) => sum + p.meld, 0); const themMeld = room.players.filter(p => p.seat % 2 === 1).reduce((sum, p) => sum + p.meld, 0); const usTotal = usMeld + room.trickPoints.us, themTotal = themMeld + room.trickPoints.them; if (room.bidWinner % 2 === 0) { room.scores.us += usTotal >= room.bid ? usTotal : -room.bid; room.scores.them += themTotal; } else { room.scores.them += themTotal >= room.bid ? themTotal : -room.bid; room.scores.us += usTotal; } room.handsInGame++; room.phase = 'round-result'; room.message = `Hand ${room.handsInGame}/4 complete. Us ${usTotal}, Them ${themTotal}.`; addEvent(room, room.message); if (room.handsInGame === 4) return setTimeout(() => finishGame(room), 3000); setTimeout(() => startRound(room), 3000); }
function finishGame(room) { const winner = room.scores.us === room.scores.them ? 'tie' : room.scores.us > room.scores.them ? 'us' : 'them'; room.gameWinners.push(winner); room.phase = 'game-result'; room.message = `Game ${room.gameNumber} complete: ${winner === 'tie' ? 'tied' : winner === 'us' ? 'Us win' : 'Them win'} (${room.scores.us}–${room.scores.them}).`; addEvent(room, room.message); if (room.gameNumber === 1) return setTimeout(() => startNewGame(room), 3500); if (room.gameNumber === 2 && room.gameWinners[0] !== winner) { room.message += ' Tiebreaker game starts next.'; addEvent(room, 'The first two games had different winners; starting a tiebreaker.'); return setTimeout(() => startNewGame(room), 3500); } room.phase = 'match-complete'; room.message += ` ${winner === 'tie' ? 'Match remains tied.' : winner === 'us' ? 'Us win the match.' : 'Them win the match.'}`; addEvent(room, room.message); }
function startNewGame(room) { room.gameNumber++; room.handsInGame = 0; room.scores = { us: 0, them: 0 }; room.dealer = (room.dealer + 2) % 4; startRound(room, false); }
function startRound(room, advanceDealer = true) { if (advanceDealer) room.dealer = (room.dealer + 1) % 4; room.phase = 'bidding'; room.bid = 20; room.bidWinner = null; room.passes = 0; room.active = [true, true, true, true]; room.trump = null; room.turn = (room.dealer + 1) % 4; room.trick = []; room.lastTrick = []; room.tricks = 0; room.lastWinner = 0; room.trickPoints = { us: 0, them: 0 }; const deck = shuffle(makeDeck()); room.players.forEach(player => { player.hand = sortHand(deck.splice(0, 12)); player.meld = 0; player.meldCards = []; }); room.message = `${room.players[room.dealer].name} deals game ${room.gameNumber}, hand ${room.handsInGame + 1}.`; addEvent(room, room.message); runAi(room); }
function showMeldResult(room) { if (!room.players.every(p => p.meld !== null)) return; if (room.bidWinner === null) { room.bidWinner = room.dealer; room.bid = 20; } room.phase = 'meld-result'; room.turn = null; room.message = 'Meld revealed. Review the totals, then begin trick play.'; }
function chooseTrump(room, trump) { room.trump = trump; room.phase = 'meld'; room.turn = 0; room.players.forEach(p => { p.meld = p.ai ? countMeld(p.hand, trump) : null; p.meldCards = p.ai ? scoringCards(p.hand, trump) : []; }); room.message = `${room.players[room.bidWinner ?? room.dealer].name} chooses ${SUIT_SYMBOLS[trump]} as trump.`; addEvent(room, room.message); runAi(room); }
function finishTrick(room) { const winner = trickWinner(room.trick, room.trump); room.trickPoints[winner.seat % 2 ? 'them' : 'us'] += room.trick.reduce((sum, play) => sum + cardPoints(play.card.rank), 0); room.lastWinner = winner.seat; room.lastTrick = room.trick; room.trick = []; room.tricks++; room.turn = winner.seat; room.phase = 'trick-result'; room.message = `${winner.player} wins the trick.`; addEvent(room, room.message); if (room.tricks === 12) return setTimeout(() => finishRound(room), 1600); setTimeout(() => { if (room.phase !== 'trick-result') return; room.phase = 'playing'; room.lastTrick = []; runAi(room); }, 1600); }
function runAi(room) { while (room.phase === 'bidding' && room.players[room.turn].ai) { const player = room.players[room.turn]; const maximum = Math.max(...SUITS.map(suit => countMeld(player.hand, suit))) + 10; const bid = room.bid < maximum && room.bid < 30 ? room.bid + 1 : 0; if (bid) { room.bid = bid; room.bidWinner = player.seat; room.message = `${player.name} bids ${bid}.`; addEvent(room, room.message); } else { room.active[player.seat] = false; room.message = `${player.name} passes.`; addEvent(room, room.message); } room.turn = (room.turn + 1) % 4; finishBidding(room); while (room.phase === 'bidding' && !room.active[room.turn]) room.turn = (room.turn + 1) % 4; } if (room.phase === 'trump' && room.players[room.turn].ai) { const player = room.players[room.turn]; chooseTrump(room, SUITS.reduce((best, suit) => countMeld(player.hand, suit) > countMeld(player.hand, best) ? suit : best, 0)); return; } while (room.phase === 'meld' && room.players[room.turn].ai) room.turn = (room.turn + 1) % 4; if (room.phase === 'meld') showMeldResult(room); if (room.phase === 'playing' && room.players[room.turn].ai) setTimeout(() => { if (room.phase !== 'playing' || !room.players[room.turn].ai) return; const player = room.players[room.turn], card = aiMove(player, room.trick, room.trump); player.hand.splice(player.hand.indexOf(card), 1); room.trick.push({ player: player.name, seat: player.seat, card }); room.message = `${player.name} plays ${card.rank}${SUIT_SYMBOLS[card.suit]}.`; addEvent(room, room.message); room.turn = (room.turn + 1) % 4; if (room.trick.length === 4) finishTrick(room); runAi(room); }, 900); }
function createRoom(name) { const aiNames = shuffle(['Bruce', 'Dick', 'Tim']); const players = [0, 1, 2, 3].map(seat => ({ id: crypto.randomUUID(), name: seat === 2 ? (name || 'You') : `${aiNames.pop()} (AI)`, ai: seat !== 2, seat, hand: [], meld: 0, meldCards: [] })); const room = { code: newCode(), dealer: Math.floor(Math.random() * 4), gameNumber: 1, handsInGame: 0, gameWinners: [], phase: 'bidding', bid: 20, bidWinner: null, passes: 0, active: [true, true, true, true], turn: 0, trump: null, trick: [], lastTrick: [], tricks: 0, lastWinner: 0, trickPoints: { us: 0, them: 0 }, scores: { us: 0, them: 0 }, message: 'Your table is ready.', history: [], players }; room.turn = (room.dealer + 1) % 4; const deck = shuffle(makeDeck()); players.forEach(player => { player.hand = sortHand(deck.splice(0, 12)); }); room.message = `${players[room.dealer].name} deals game 1, hand 1.`; addEvent(room, room.message); rooms.set(room.code, room); runAi(room); return room; }

function readBody(req) { return new Promise(resolve => { let text = ''; req.on('data', chunk => text += chunk); req.on('end', () => { try { const body = JSON.parse(text || '{}'); resolve({ ...body, cardIds: Array.isArray(body.cardIds) ? body.cardIds : [] }); } catch { resolve({ cardIds: [] }); } }); }); }
function send(res, status, body) { res.writeHead(status, { 'content-type': 'application/json' }); res.end(JSON.stringify(body)); }
function serveFile(req, res) { const url = new URL(req.url, 'http://localhost'); const requested = url.pathname === '/' ? '/index.html' : url.pathname; const file = path.join(__dirname, 'web', path.normalize(requested).replace(/^\/+/, '')); if (!file.startsWith(path.join(__dirname, 'web'))) return send(res, 403, { error: 'forbidden' }); fs.readFile(file, (error, data) => { if (error) return send(res, 404, { error: 'not found' }); res.writeHead(200, { 'content-type': file.endsWith('.css') ? 'text/css' : file.endsWith('.js') ? 'text/javascript' : 'text/html', 'cache-control': 'no-store' }); res.end(data); }); }

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`); const parts = url.pathname.split('/').filter(Boolean);
  if (req.method === 'POST' && url.pathname === '/api/rooms') { const input = await readBody(req), room = createRoom(input.name); const player = room.players[2]; return send(res, 201, { playerId: player.id, room: view(room, player.id) }); }
  if (parts[0] !== 'api' || parts[1] !== 'rooms' || !parts[2]) return serveFile(req, res);
  const room = rooms.get(parts[2].toUpperCase()); if (!room) return send(res, 404, { error: 'room not found' });
  if (req.method === 'GET') return send(res, 200, { room: view(room, url.searchParams.get('playerId')) });
  if (req.method === 'POST' && parts[3] === 'join') { const input = await readBody(req), player = room.players.find(p => p.ai); if (!player) return send(res, 409, { error: 'table is full' }); player.ai = false; player.name = input.name || 'Player'; player.id = crypto.randomUUID(); return send(res, 200, { playerId: player.id, room: view(room, player.id) }); }
  if (req.method !== 'POST' || parts[3] !== 'actions') return send(res, 404, { error: 'not found' });
  const input = await readBody(req), player = room.players.find(p => p.id === input.playerId);
  if (!player || player.ai || (room.phase !== 'meld-result' && player.seat !== room.turn)) return send(res, 400, { error: 'not your turn' });
  if (room.phase === 'bidding' && ['bid', 'pass'].includes(input.type)) { const bid = input.type === 'pass' ? 0 : Number(input.value); if (bid && bid <= room.bid) return send(res, 400, { error: 'bid must exceed current bid' }); if (bid) { room.bid = bid; room.bidWinner = player.seat; room.message = `${player.name} bids ${bid}.`; } else { room.active[player.seat] = false; room.message = `${player.name} passes.`; } addEvent(room, room.message); room.turn = (room.turn + 1) % 4; finishBidding(room); while (room.phase === 'bidding' && !room.active[room.turn]) room.turn = (room.turn + 1) % 4; runAi(room); }
  else if (room.phase === 'trump' && input.type === 'trump') chooseTrump(room, Math.max(0, Math.min(3, Number(input.value))));
  else if (room.phase === 'meld' && input.type === 'meld') { const submitted = player.hand.filter(card => input.cardIds.includes(card.id)); player.meld = countMeld(submitted, room.trump); player.meldCards = scoringCards(submitted, room.trump); room.message = `${player.name} exposed ${player.meld} meld points.`; addEvent(room, room.message); room.turn = (room.turn + 1) % 4; runAi(room); showMeldResult(room); }
  else if (room.phase === 'meld-result' && input.type === 'continue') { room.phase = 'playing'; room.turn = room.bidWinner; room.message = 'Meld counted. The bid winner leads.'; runAi(room); }
  else if (room.phase === 'playing' && input.type === 'play') { const card = player.hand.find(c => c.id === input.cardId); if (!card || !legalCards(player.hand, room.trick, room.trump).some(c => c.id === card.id)) return send(res, 400, { error: 'card is not legal for this trick' }); player.hand.splice(player.hand.indexOf(card), 1); room.trick.push({ player: player.name, seat: player.seat, card }); room.message = `${player.name} plays ${card.rank}${SUIT_SYMBOLS[card.suit]}.`; addEvent(room, room.message); room.turn = (room.turn + 1) % 4; if (room.trick.length === 4) finishTrick(room); runAi(room); }
  return send(res, 200, { room: view(room, player.id) });
});
server.listen(PORT, () => console.log(`Pinochle web server listening on http://localhost:${PORT}`));
