const $ = s => document.querySelector(s);
let roomCode = '', playerId = '', timer, selectedMeld = new Set();
const names = ['north', 'east', 'south', 'west'];
const label = rank => ({ 11: 'J', 12: 'Q', 13: 'K', 14: '10', 15: 'A' }[rank] || rank);
const suitSymbol = suit => ['♣', '♦', '♥', '♠'][suit] || '';
const suitOrder = suit => [0, 1, 3, 2].indexOf(suit);

async function request(url, options) { const r = await fetch(url, { ...options, headers: { 'content-type': 'application/json' } }); const b = await r.json(); if (!r.ok) { const error = new Error(b.error || 'Request failed'); error.status = r.status; throw error; } return b; }
function enter(room, id) { roomCode = room.code; playerId = id; $('#room-code').textContent = roomCode; $('#lobby').classList.add('hidden'); $('#game').classList.remove('hidden'); render(room); clearInterval(timer); timer = setInterval(refresh, 900); }
function render(room) {
  if (room.phase !== 'meld') selectedMeld.clear();
  const mine = room.players.find(p => p.id === playerId); const displaySeat = seat => (seat - (mine?.seat ?? 2) + 6) % 4; const myTurn = mine && room.turn === mine.seat;
  room.players.forEach(p => { const seat = names[displaySeat(p.seat)]; const target = $(`#${seat}-name`); if (target) target.textContent = p.name; const meld = $(`#${seat}-meld`); if (meld) meld.textContent = `meld ${p.meld}`; });
  $('#hand').className = 'hand seat-2';
  $('#bid').textContent = room.bid; $('#phase').textContent = room.phase[0].toUpperCase() + room.phase.slice(1); $('#message').textContent = room.message; $('#us-score').textContent = room.scores.us; $('#them-score').textContent = room.scores.them; $('#trump').textContent = room.trump == null ? 'Not chosen' : ['♣ Clubs', '♦ Diamonds', '♥ Hearts', '♠ Spades'][room.trump];
  $('#dealer').textContent = room.players.find(p => p.seat === room.dealer)?.name || '—'; $('#bid-winner').textContent = room.bidWinner == null ? '—' : `${room.players.find(p => p.seat === room.bidWinner)?.name || '—'} (${room.bid})`;
  const teams = [[0, 2, 'Us — North + South'], [1, 3, 'Them — East + West']]; $('#meld-list').replaceChildren(...teams.map(([first, second, title]) => { const members = room.players.filter(p => p.seat === first || p.seat === second); const item = document.createElement('li'); const total = members.reduce((sum, p) => sum + p.meld, 0); const cards = members.map(p => `${p.name}: ${(p.meldCards || []).map(c => `${label(c.rank)}${suitSymbol(c.suit)}`).join(' ') || '—'}`).join(' · '); item.textContent = `${title}: ${total} (${cards})`; return item; })); $('#activity').replaceChildren(...(room.history || []).slice().reverse().map(text => { const item = document.createElement('li'); item.textContent = text; return item; }));
  const sortedHand = (room.hand || []).slice().sort((a, b) => suitOrder(a.suit) - suitOrder(b.suit) || a.rank - b.rank);
  $('#hand').replaceChildren(...sortedHand.map(c => { const el = document.createElement('button'); const redSuit = c.suit === 1 || c.suit === 2; el.className = `card ${redSuit ? 'red' : 'black'}${selectedMeld.has(c.id) ? ' selected' : ''}`; el.style.color = redSuit ? '#b53b45' : '#202a45'; el.textContent = `${label(c.rank)}${suitSymbol(c.suit)}`; const selectingMeld = room.phase === 'meld' && myTurn; el.disabled = room.phase === 'complete' || (!selectingMeld && (room.phase !== 'playing' || !myTurn)); el.onclick = () => selectingMeld ? (selectedMeld.has(c.id) ? selectedMeld.delete(c.id) : selectedMeld.add(c.id), render(room)) : act({ type: 'play', cardId: c.id }); return el; }));
  room.players.forEach(p => { const reveal = $(`#${names[displaySeat(p.seat)]}-reveal`); const visible = room.phase === 'meld-result'; reveal.replaceChildren(...(visible ? p.meldCards : []).map(c => { const el = document.createElement('div'); const redSuit = c.suit === 1 || c.suit === 2; el.className = `mini-card ${redSuit ? 'red' : 'black'}`; el.textContent = `${label(c.rank)}${suitSymbol(c.suit)}`; return el; })); reveal.classList.toggle('hidden', !visible); });
  const visibleTrick = room.trick.length ? room.trick : (room.lastTrick || []); $('#played').replaceChildren(...visibleTrick.map(x => { const el = document.createElement('div'); const value = document.createElement('span'); const owner = document.createElement('small'); const redSuit = x.card.suit === 1 || x.card.suit === 2; el.className = `card played-card seat-${displaySeat(x.seat)} ${redSuit ? 'red' : 'black'}`; el.style.color = redSuit ? '#b53b45' : '#202a45'; value.textContent = `${label(x.card.rank)}${suitSymbol(x.card.suit)}`; owner.textContent = x.player; el.append(value, owner); return el; }));
  const bid = $('#bid-button'); const bidInput = $('#bid-input'); bidInput.min = room.bid + 1; if (Number(bidInput.value) <= room.bid) bidInput.value = room.bid + 1; bidInput.disabled = !myTurn || room.phase !== 'bidding'; bid.disabled = !myTurn || !['bidding', 'trump'].includes(room.phase); bid.textContent = room.phase === 'bidding' ? `Bid ${bidInput.value}` : room.phase === 'trump' ? 'Choose trump' : 'Playing'; bidInput.oninput = () => { if (room.phase === 'bidding') bid.textContent = `Bid ${bidInput.value}`; }; bid.onclick = () => room.phase === 'trump' ? act({ type: 'trump', value: $('#trump-select').value }) : act({ type: 'bid', value: Number(bidInput.value) });
  $('#pass-button').disabled = !myTurn || room.phase !== 'bidding'; $('#pass-button').onclick = () => act({ type: 'pass' }); const meldButton = $('#meld-button'); const showingMeld = room.phase === 'meld' && myTurn; const showingResult = room.phase === 'meld-result'; meldButton.classList.toggle('hidden', !showingMeld && !showingResult); meldButton.disabled = !showingMeld && !showingResult; meldButton.textContent = showingResult ? 'Begin trick play' : 'Submit meld'; meldButton.onclick = () => { if (showingResult) return act({ type: 'continue' }); selectedMeld = new Set([...selectedMeld].filter(id => sortedHand.some(c => c.id === id))); act({ type: 'meld', cardIds: [...selectedMeld] }); };
}
function returnToLobby(message) { clearInterval(timer); selectedMeld.clear(); roomCode = ''; playerId = ''; $('#game').classList.add('hidden'); $('#lobby').classList.remove('hidden'); $('#room-hint').textContent = message; }
async function refresh() { try { render((await request(`/api/rooms/${roomCode}?playerId=${playerId}`)).room); } catch (e) { if (e.status === 404) return returnToLobby('That room is no longer available. Create or join a new table.'); $('#message').textContent = e.message; } }
async function act(action) { try { render((await request(`/api/rooms/${roomCode}/actions`, { method: 'POST', body: JSON.stringify({ ...action, playerId }) })).room); } catch (e) { $('#message').textContent = e.message; } }
$('#create').onclick = async () => { try { const d = await request('/api/rooms', { method: 'POST', body: JSON.stringify({ name: $('#name').value, players: 4 }) }); enter(d.room, d.playerId); } catch (e) { $('#room-hint').textContent = e.message; } };
$('#join').onclick = async () => { try { const code = $('#room-input').value.trim().toUpperCase(); const d = await request(`/api/rooms/${code}/join`, { method: 'POST', body: JSON.stringify({ name: $('#name').value }) }); enter(d.room, d.playerId); } catch (e) { $('#room-hint').textContent = e.message; } };
$('#leave').onclick = () => returnToLobby('');
